puts "The students of my cohort at Makers Academy"
puts "Gabe"
puts "..... "
puts "Jordan"
puts "Sam"
puts "Matthew"
puts "Mark"
puts "Luke"
puts "John"
puts "etc. etc. etc."
puts ""
print "Overall, we have"
print 9
print " great students"